collections:
  navigation:
    output: true
  people:
    output: true
  jobs:
    output: true
    permalink: /jobs/:name/
  quotes:
    output: true

# Permalink structure for _posts
permalink: /news/:title/

baseurl: ""

timezone: Europe/Zurich

exclude:
  - node_modules
  - .git
  - /netfabric_site.zip
  - /README.md

google_analytics_tag_id: G-61H18LPX39
google_tag_manager_container_id: GTM-WBM46568


paginate: 5 # Number of posts per page
paginate_path: "/post/page:num/" # Path for paginated pagess
